### ISSUE TITLE
Duplicate import of obs-studio-node module in src\worker\obs.ts

### ISSUE THREAD

**Issue by alokmahor** [hrueger/AGView#29]
What is purpose of import of `obs-studio-node` module two times in [src\worker\obs.ts](https://github.com/hrueger/AGView/blob/master/src/worker/obs.ts)?

```
import * as osn from "obs-studio-node";
import { ISceneItem, ITransition } from "obs-studio-node";
```
Can we access `ISceneItem` and `ITransition` like `osn.ISceneItem` and `osn.ITransition` from first import?

**Comment by hrueger** [comment]
I believe we can, I'll check.

**Comment by hrueger** [comment]
I changed it in #39. @alokmahor you were right, there's no difference. I guess it happened by VSCode's auto import suggestions.
