### ISSUE TITLE
Where can I see output of echo in electron-builder custom NSIS include script?

### ISSUE THREAD

**Issue by alokmahor** [hrueger/AGView#31]
I want to perform some action on uninstallation of this electron app.
So I added custom NSIS include script `installer.nsh` and its content is 
```
!macro customUnInstall
  !echo "test output"
!macroend
```
By following https://www.electron.build/configuration/nsis I have added this entry also in [electron-builder.json](https://github.com/hrueger/AGView/blob/master/electron-builder.json) like 
```
"nsis": { "include": "installer.nsh" }
```
On uninstall of this app I am not seeing `test output` anywhere. Where can I see this output?

**Comment by hrueger** [comment]
Hi @alokmahor,
I've never tried nsis scripts and therefore I don't have any experience with them. Why don't you create an issue in the `electron-builder` repository?

**Comment by alokmahor** [comment]
I have posted `electron-builder` repo
Thank you

**Comment by alokmahor** [comment]
Do you have any idea on this https://github.com/Envek/obs-studio-node-example/issues/38

**Comment by hrueger** [comment]
No, sorry. Why would you want to have a 32bit version?

**Comment by alokmahor** [comment]
Because I need 32bit virtual camera

**Comment by alokmahor** [comment]
Do you have any idea on https://github.com/electron-userland/electron-builder/issues/5707 ?
