### ISSUE TITLE
Image source not working

### ISSUE THREAD

**Issue by alokmahor** [hrueger/AGView#32]
I tried to add `iamge_source` by taking help from this project but its not working for me. I am seeing black color only in preview.
```
const logoSource = osn.InputFactory.create("image_source", "image_source_id", { file: "C:\Users\alokm\Downloads\Krishna.jpg" });
const scene = osn.SceneFactory.create('test-scene');
const sceneItem = scene.add(logoSource);
osn.Global.setOutputSource(0, scene);
```
What I am missing? `monitor_capture` and `window_capture` as source are working fine but not `image_source`.

**Comment by hrueger** [comment]
If you download the latest release and run it, can you see the logo? If yes, something with your code must be wrong.

**Comment by hrueger** [comment]
@alokmahor And please don't create those issues here (as it is not a problem of AGView). Instead, use https://github.com/Envek/obs-studio-node-example and if something with the (newly created) documentation is wrong, use https://github.com/hrueger/obs-studio-node-docs

**Comment by alokmahor** [comment]
Thank you @hrueger for creating https://github.com/hrueger/obs-studio-node-docs. I will not create issue here now.
