### ISSUE TITLE
Add video source status and actions

### ISSUE THREAD

**Issue by hrueger** [hrueger/AGView#43]
- current time
- time left
- play
- resume
- pause

**Comment by hrueger** [comment]
see https://github.com/stream-labs/obs-studio-node/issues/887

**Comment by rosendolu** [comment]
I can't found below attributes among video source .Where did you get this? Further, Is there a way to update the `video source` settings fields?   issue at https://github.com/stream-labs/obs-studio-node/pull/1385#issuecomment-2095605990
1. current time
2. time left
