### ISSUE TITLE
When I add a camera resource, how to choose it

### ISSUE THREAD

**Issue by bbc-594** [hrueger/AGView#55]
```JavaScript
// tell OBS which sceneItems are selected 

scene.getObsScene().getItems().forEach(obsSceneItem => {
      obsSceneItem.selected = activeObsIds.includes(obsSceneItem.id);
 });
```

I saw this code in the streamlabs-obs project, and then the scene-item on the interface was selected, but after I set the selected of my scene-item to true, the same effect could not appear

**Comment by hrueger** [comment]
HI @bbc-594,
I don't completely understand what you're trying to do ;-) As I think it is not about `AGView` but rather about `obs-studio-node`, could you please move that issue to https://github.com/Envek/obs-studio-node-example? This is where we all test and try to reverse engineer `obs-studio-node`. Thanks!

**Comment by bbc-594** [comment]
> HI @bbc-594,
> I don't completely understand what you're trying to do ;-) As I think it is not about `AGView` but rather about `obs-studio-node`, could you please move that issue to https://github.com/Envek/obs-studio-node-example? This is where we all test and try to reverse engineer `obs-studio-node`. Thanks!

ok, thank you
